name: Training Plots
description: Creates plots for data generated during the training process

inputs:
- {name: Model Dir 0 , type: Data, description: 'Directory where training data is saved for model 0'}
- {name: Model Dir 1 , type: Data, description: 'Directory where training data is saved for model 1'}
- {name: Model Name 0 , type: String, description: 'Name for model 0'}
- {name: Model Name 1 , type: String, description: 'Name for model 1'}

outputs:
- {name: Output Dir, type: Data, description: 'Output data path'}

implementation:
    container:
        image: cesarsalcedo/cs3p02_kubeflow_project@sha256:efa221e4916712f1b32d434697bb8ae6a1d22859ef1c4b0b61aa8e38eac80291
        command: [
            python3,
            /pipelines/component/src/training_plots.py,
            --model-dir0,
            {inputPath: Model Dir 0 },
            --model-name0,
            {inputValue: Model Name 0 },
            --model-dir1,
            {inputPath: Model Dir 1 },
            --model-name1,
            {inputValue: Model Name 1 },
            --output,
            {outputPath: Output Dir},
        ]